### ISSUE TITLE
[SLAM] Reject invalid options and keep internal options unchanged 

### ISSUE THREAD

**Issue by haoyunfeix** [01org/node-realsense#110]
Kenny:

> Ref: https://github.com/01org/node-realsense/issues/109
> 
> No test case yet, just log this according to the analysis in our meeting. If there is no such bug, please close it directly.

**Comment by DonnaWuDongxia** [comment]
I think #164 has resolve this issue. @haoyunfeix would you please help to verify it?

**Comment by DonnaWuDongxia** [comment]
Move out of this milestone, @haoyunfeix please help to verify it after the release.

**Comment by haoyunfeix** [comment]
Sorry for the late feedback, this issue has been fixed with the latest code.
So close this issue.
