### ISSUE TITLE
[Sample][SLAM] Missing the 'input' and 'tracking' status in browser

### ISSUE THREAD

**Issue by haoyunfeix** [01org/node-realsense#113]
Missing the `input` and `tracking` status in browser when running sample of [slam_tutorial_1_web] on Joule Board with 0.8.0 release, this issue cannot reproduce on native.
native:
![native](https://cloud.githubusercontent.com/assets/7088194/23153989/7ee3c0c4-f846-11e6-9376-41b63a04f0bb.png)
0.8.0 release:
![0 8 0_release](https://cloud.githubusercontent.com/assets/7088194/23154126/2479fecc-f847-11e6-99f1-a8b6622acafc.png)

**Comment by DonnaWuDongxia** [comment]
Is this means the camera pose is floating while actually the camera hasn't been moved?

**Comment by haoyunfeix** [comment]
Oh, I mean the status bars (on top of Fisheye snapshot) didn't show data.
Input: fish, depth, gyr., acc.
Output: depth

**Comment by DonnaWuDongxia** [comment]
It's in expectation that we have no Input: fish, depth, gyr., acc.
The depth Output should be ready in current master, would you please verify it? @haoyunfeix

**Comment by haoyunfeix** [comment]
Verified with master branch, close this issue.
