### ISSUE TITLE
Refine document and remove duplicated content with native SDK guide

### ISSUE THREAD

**Issue by haoyunfeix** [01org/node-realsense#116]
From @halton : Can we remove some duplicated steps described in https://software.intel.com/sites/products/realsense/intro/getting_started.html and reference there directly?

**Comment by halton** [comment]
Agree, @haoyunfeix do you mind create PR?

**Comment by haoyunfeix** [comment]
Already done in https://github.com/01org/node-realsense/commit/2a49e0bd38950becc0f154d0f28613bee0bd479c, close this issue.
