### ISSUE TITLE
Remove unnecessary dep in src/person-tracking/package.json

### ISSUE THREAD

**Issue by kenny-y** [01org/node-realsense#136]
```
  "devDependencies": {
    "express": "^4.14.0",
    "socket.io": "^1.5.1",
    "spawn-npm-install": "^1.2.0",
    "tmp": "0.0.31"
  }
```
Is `socket.io` or `express` really necessary for development?

Note: `npm install` without `--saveXXX` might be able to address your requirement.

**Comment by kenny-y** [comment]
@tingshao Assignee field doesn't work, please take a quick look. Thanks.

**Comment by tingshao** [comment]
They are obsolete, I will remove them, thanks for find this.
