### ISSUE TITLE
Make any number of the 3 add-on(s) work at the same time (multi-model support)

### ISSUE THREAD

**Issue by kenny-y** [01org/node-realsense#145]
Could be:
- OR + PT
- OR + SLAM
- OR + PT + SLAM
- PT + SLAM

librealsense add-on: TBD

**Comment by kenny-y** [comment]
Started working on this today... aims to achieve a quick prototype within days...

**Comment by kenny-y** [comment]
Process level object singleton sharing across multiple builds -  done
New delegate class of camera control - able to run on single add-on.

**Comment by kenny-y** [comment]
Enabled first working prototype of 2 add-ons runing side by side. @halton @DonnaWuDongxia @tingshao @lisa0314 

![image](https://cloud.githubusercontent.com/assets/3302320/23793463/5fc0bd22-05c6-11e7-9e71-48c78126c576.png)

**Comment by tingshao** [comment]
Excited to know that!

**Comment by halton** [comment]
Super

**Comment by kenny-y** [comment]
Hit more core dump than before, after enabled PT + OR work together. The source line is: 

https://github.com/BVLC/caffe/blob/master/src/caffe/common.cpp#L58

No clue at present.

**Comment by kenny-y** [comment]
SLAM module is now able to build and run with other modules, but with an error state:

The following condition is always `true` in frame_callback @DonnaWuDongxia 

```
if (rs::timestamp_domain::microcontroller != timestampDomain) {
```

In https://github.com/IntelRealSense/librealsense/blob/master/doc/whats_new.md, it says
>In order to receive proper timestamps from the microcontroller fisheye_strobe option must be toggled on.

And the key point is to `device->start()` with `rs::source == 2 (all_sources)`

Note: the above issue only occurs when SLAM is started later than OR/PT module.

**Comment by kenny-y** [comment]
Finally made 3 addons work together, with arbitrary startup sequence -- formerly there was a limitation that SLAM must be started up as the 1st addon.

Please be noted that I believe the orthogonal solution is the most elegant one...

**Comment by kenny-y** [comment]
Introduced a new helper class to manage the requirement among different add-ons, will PR tomorrow to make sure that I'm lucent...

**Comment by kenny-y** [comment]
`mocha` failed on individual add-on (running in `nodejs` is OK), need to figure it out... PR is pending...
