### ISSUE TITLE
[Doc] Typo in README files

### ISSUE THREAD

**Issue by haoyunfeix** [01org/node-realsense#193]
1.　Change `console.log('New object recognized': evtData);` like `console.log('New object recognized: ', evtData);` https://github.com/01org/node-realsense/blame/master/src/object-recognition/README.md#L30

2.　Change `console.log('Person tracked': evtData);` like `console.log('Person tracked: ', evtData);` https://github.com/01org/node-realsense/blame/master/src/person-tracking/README.md#L27

3.　Change `console.log('Camera tracking': evtData.cameraPose, evtData.accuracy);` like `console.log('Camera tracking: ', evtData.cameraPose, evtData.accuracy);` https://github.com/01org/node-realsense/blame/master/src/slam/README.md#L22

**Comment by kenny-y** [comment]
Opps, good catch. Will fix.
