### ISSUE TITLE
Document for common APIs

### ISSUE THREAD

**Issue by haoyunfeix** [01org/node-realsense#94]
We have no document for common APIs, e.g. enum, interface, dictionary

Since we're getting closer and closer to release, this becomes serious.

kenny-y ：
To do this well, we also need to figure out all "supported module config" of each module and clearly list them in document... at present, SLAM is still missing that info (PT & OR are done)

**Comment by kenny-y** [comment]
It's done https://01org.github.io/node-realsense/doc/spec/common.html
